-- Crie a tabela de ranking
create table if not exists public.ranking (
  id bigint generated by default as identity primary key,
  username text not null,
  score int not null check (score >= 0 and score <= 100),
  created_at timestamp with time zone default now()
);

-- Habilite RLS (Row Level Security)
alter table public.ranking enable row level security;

-- Políticas: permitir leitura e escrita para clientes (anon e authenticated)
create policy if not exists "Allow read for everyone"
on public.ranking
for select
to anon, authenticated
using (true);

create policy if not exists "Allow insert for everyone"
on public.ranking
for insert
to anon, authenticated
with check (true);

-- Índice para ordenação por score/tempo
create index if not exists ranking_score_idx on public.ranking (score desc, created_at asc);
